### ISSUE TITLE
Blastoff.zone: Earn 1 ETH

### ISSUE THREAD

**Issue by Lirikkk** [KaganCanSit/Temel-CMake-Notlari#4]

**Comment by KaganCanSit** [comment]
@github / I have lots of emails like this!

CAUTION: Please do not believe these phishing emails. An organization like Github will not send you this type of email! Be careful when giving permissions to your Github account and the bot etc. you want to add.

Please do not click any links here. I reported this and now I'm closing it by deleting its content.
